# Generated by Django 5.2.7 on 2025-10-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='chapa_transaction_id',
        ),
    ]
